### ISSUE TITLE
[QUESTION] Athena TypeORM Tooling

### ISSUE THREAD

**Issue by 5donuts** [awslabs/aws-athena-query-federation#106]
I have a question that I don't think is related to a bug or feature request. 

I would like to use TypeORM with AWS Athena as the backend for it.

I was wondering if there were any internal tools that the AWS Athena team has for working with TypeORM that they would be willing to open source.

**Comment by avirtuos** [comment]
Can you give a bit more detail about what TypeORM is and how you'd like to use it with Athena? Based on some quick reading I'm assuming you'd like to have TypeORM support Athena has where the data is actually stored? if so, this is not something that is currently in our roadmap and is perhaps a better question for the folks that maintain TypeORM. Anecdotally, most ORMs i've worked with (e.g. Hibernate, Hive's Thrift based ORM) require write access to setup / evolve the schema the kinds of writes they expect to do may be challenging via Athena today and in some cases impossible (e.g. federation is currently read only).

**Comment by 5donuts** [comment]
My main goal with TypeORM was mostly to use it as an abstraction layer over a database to avoid having hardcoded query strings floating around the project I'm working on, especially since I anticipate needing to support more than one DBMS.

I was hoping to use Athena as the data store for part of the application as I have already set up an Athena table pointed to some S3 buckets I'm using to store a significant amount of data.

Unfortunately, since support for linking TypeORM and Athena isn't on your roadmap or the TypeORM team's roadmap, it looks like I would be better served using a different tool.

Might you have any recommendations for tools that make it easy to abstract away DB queries in a project?

**Comment by ryanrupp** [comment]
I think probably first confirm Athena is good for your workload. That is your workload is:

1. Primarily read only
2. Mainly large(r) analytical queries (think aggregations, large table scans across many rows etc.). Also, that you're okay with seconds+ for the response times rather than sub second response times. For instance PK lookups that take micro/milliseconds in a database designed for transactional workloads (relational databases, DynamoDB etc.) will likely take at least a second in Athena as it's designed for analytics workloads rather than transactional.

If your usage fits that criteria than in regards to the ORM I think a full blown ORM is probably over-kill given primarily read-only access/aggregations but I'm not familiar with what the options are in node. In Java for instance most of these libraries revolve around JDBC (standard for database access which Athena implements a driver for). There's libraries in Java that build upon JDBC for data access that are not full blown ORMs that could possibly fit well, [JOOQ](https://www.jooq.org/) comes to mind (or QueryDSL possibly) although I cannot say I've used it for building aggregation type queries but the general idea is allowing to build type safe queries.

Worst case if you just put everything behind a DAO interface so you're isolating the direct SQL usage at least and can have typed input/output so the rest of your application doesn't need to care about the internal SQL usage.

**Comment by 5donuts** [comment]
Thanks for the suggestions!

The main reason I was looking at TypeORM is because I could change what backend DB I use easily and I anticipate needing to either support multiple DBMS for this project or to refactor to something that doesn't use Athena and was hoping to do that without having to do any significant work.
But, as you said, a full blown ORM _is_ overkill, since what I'm doing with Athena at the moment is just querying on data that's sitting in S3.

**Comment by avirtuos** [comment]
One more thing I'd mention. If you want to abstract the specific SQL from your app and also want to avoid having SQL hard coded, in the past I've used [StringTemplate](https://www.stringtemplate.org/) for this. Its a pretty powerful templating engine that would easily let you have a DB specific dialect file that you replace values into and load that at runtime from your app either on the class path or elsewhere. I've specifically used it to accomplish something liek Hibernate's named queries without the need for actually having Hibernate.
