### ISSUE TITLE
NullPointerException with nested null fields with connector DynamoDB

### ISSUE THREAD

**Issue by rradman** [awslabs/aws-athena-query-federation#112]
**Describe the bug**
The connector works just fine until I try to query a table that has a nested NULL field inside of a JSON object (in DynamoDB its of type 'Map').
An example is bellow.

**To Reproduce**
1. Create a DynamoDB table.
2. Create the following item:
```
{
  "id": "not_working",
  "some_json": {
    "nested_null_value": null
  },
  "top_layer_null": null
}
```
3. Deploy Athena DynamoDB connector.
4. Query the table from Athena console.
4. Error occurs.

**Expected behavior**
I would expect to get a response in the Athena console, but instead I get the error.

**Screenshots / Exceptions / Errors**
Your query has the following error(s):
GENERIC_USER_ERROR: Encountered an exception[java.lang.NullPointerException] from your LambdaFunction[dynamo_catalog] executed in context[retrieving meta-data] with message[java.lang.NullPointerException]

**Connector Details (please complete the following information):**
 - Version: 2020.04.01
 - Name AthenaDynamoDBConnector

**Comment by avirtuos** [comment]
Thanks for raising this. I suspect this is related to the fact that you have null values some fields. The error message needs to be improved though. Since DDB is essentially schema less the connector attempts to infer schema by reading a few rows and looking at the values. 

We will take a deeper look and confirm if this is indeed the case and why the connector isn't handling it more gracefully by ignoring the column or coercing the column to a safe type like string. 

To aid us in investigating, can you provide us with the logs from cloudwatch logs for the Lambda function which correspond to this query? Those logs will contain a more complete exception with stacktrace amongst other useful info. 

As a work around, you can define the schema of this DDB table in Glue. That will cause the connector to bypass it's schema inference capability and perhaps stop the error so you can continue your work while we investigate.

**Comment by rradman** [comment]
[lambda_logs.txt](https://github.com/awslabs/aws-athena-query-federation/files/4236166/lambda_logs.txt)
You can see the logs in the link above.

> As a work around, you can define the schema of this DDB table in Glue. That will cause the connector to bypass it's schema inference capability and perhaps stop the error so you can continue your work while we investigate.

Your workaround does work for this case, thanks.

**Comment by avirtuos** [comment]
Created a PR to improve the error messages. The NPE was actually from the error message creation and masked the actual issue (schema inference failure).

**Comment by avirtuos** [comment]
Closing in favor of 115
