### ISSUE TITLE
java.lang.RuntimeException with nested numbers - DynamoDB connector

### ISSUE THREAD

**Issue by rradman** [awslabs/aws-athena-query-federation#115]
Logs from the lambda function:
[lambda_logs.txt](https://github.com/awslabs/aws-athena-query-federation/files/4244067/lambda_logs.txt)

**Describe the bug**
Having a nested number in DynamoDB causes glue crawler to create an invalid schema, resulting in DynamoDB connector failure.

**To Reproduce**
1. Create a DynamoDB table with the following item:
```
{
  "id": "secret_id",
  "some_number": 123,
  "some_object": {
    "nested_number": 456
  }
}
```
2. Create a Glue Crawler and let it crawl the table and create a schema
3. The schema ends up looking like this:

```
"FieldSchema": [
				{
					"name": "some_number",
					"type": "bigint",
					"comment": ""
				},
				{
					"name": "some_object",
					"type": "struct<nested_number:bigint>",
					"comment": ""
				},
				{
					"name": "id",
					"type": "string",
					"comment": ""
				}
			]
```
4. Use a DynamoDB connector from Athena and receive the following error: 

> java.lang.RuntimeException

Notice that both "some_number" and "nested_number" got recognized as BIGINT type by the Glue Crawler, which seems to be incorrect.

**Screenshots / Exceptions / Errors**
Your query has the following error(s):

GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[function_name] executed in context[S3SpillLocation{bucket='bucket-name', key='athena-spill/*******-*******-*******-**************/*******-*******-*******-*******-*******', directory=true}] with message[Error while processing field some_object]

**Connector Details (please complete the following information):**
 - Version: 2020.04.01
 - Name: AthenaDynamoDBConnector

**Additional context**
Querying the mentioned DynamoDB table without using a Glue Schema works without throwing any errors, the response looks like this:

> some_number: 123.000000000
> some_object: {nested_number=456.000000000}
> id: secret_id

Notice that both integers seem to be shown as DOUBLE type.

Also, because of the issue #112 I'm forced to use Glue Crawler schema to query the DynamoDB tables, which is why I am basically stuck. Any work around ideas are welcome, thanks.

**Comment by avirtuos** [comment]
You can manually (without crawler) edit the schema in glue and set the fields to their appropriate type. Have you tried that?

@atennak1 any thoughts on this type mismatch?

**Comment by rradman** [comment]
I've tried changing it to INT, DECIMAL and TIMESTAMP, none of them worked (same Error).
Example with INT:
`struct<nested_number:int> `
Is that what you suggested?

**Comment by avirtuos** [comment]
What is it stored as in Dynamo? Seemed like a double in your earlier post. Have you tried double?

**Comment by rradman** [comment]
I just did, it throws the same error.
In DynamoDB table they look like integers to me (simply 123 and 456), but I'm not sure how to check the actual type. By looking at the table it only says "Number" as type.
Example:
`nested_number Number: 456`

**Comment by avirtuos** [comment]
Ok, thanks. We will have an engineer look into this.

**Comment by rradman** [comment]
Hi guys, any progress on this?

**Comment by avirtuos** [comment]
@rradman , not yet. We are working towards closing all blocking items on the road to General Availability. We have this on our list but it may take some time for an engineer to free up and investigate it. 

@soojinj let's chat about if this is something we can fit between your other tasks since you recently investigated a similar issue you might have enough context to make this quick.

**Comment by atennak1** [comment]
Non decimal types numeric are only being handled at the top level: https://github.com/awslabs/aws-athena-query-federation/blob/d3b25cb6bef865f51cfd5e19e9d9512b29f48015/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java#L162-L164

Instead of adding more code/branches for nested types, we should apply the Extractor framework to the DDB connector.

**Comment by avirtuos** [comment]
@soojinj  see akila's comment, this make sense for that issue you are creating.

**Comment by rradman** [comment]
@atennak1 I've tried the workaround you suggested but it doesn't help - getting the **ResourceNotFoundException** error. 
Is there anything else I can try?

**Comment by avirtuos** [comment]
@rradman what is the full error message (it might be in your cloudwatch logs for the lambda function) and can you share the request id that was met with ResourceNotFoundException

**Comment by rradman** [comment]
[lambda_logs_2.txt](https://github.com/awslabs/aws-athena-query-federation/files/4297346/lambda_logs_2.txt)

The logs you requested.

**Comment by atennak1** [comment]
Bah it looks like we don't support the decimal type in our Glue schema parser.  Something else we may need to fix.  Sorry for the broken workaround.

Another workaround you can try is to change the type to `struct<nested_number:string>` so that the BIGINTs get outputed as VARCHARs.  You can then CAST to INTEGERs if necessary to filter/function.

**Comment by rradman** [comment]
That doesn't seem to work either because changing nested_number's type to **string** causes the returned value to be **null**.
Example:
`{nested_number=null}`

Anything else I can try?
