### ISSUE TITLE
Creating a connector of connectors

### ISSUE THREAD

**Issue by rgibbard** [awslabs/aws-athena-query-federation#1187]
Is it possible to create a custom connector that delegates to one or more other connectors? The idea being to make use of one or more of the current connectors to create a custom aggregating connector? Obviously you could perform aggregation at the end-user query level by writing a query against multiple sources, but I have something in mind where that would be burdensome.

**Comment by hackett123** [comment]
Hi rgibbard@,

It sounds like your proposal for this uber-connector has two components. The first is to make it simpler to delegate parts of queries to their respective data sources, and the second is to perform operations and aggregations with the data received from its sub-connectors.

Addressing the first point, there is not actually any value to be gained here. The reason for this is that in every Athena SQL query, users already are either implicitly or explicitly specifying the datasource/connector where the data lives, the schema in that connector, and the table in that schema which they want to query. So, adding an uber-connector where to delegate data is not going to do anything because users already specify this information.

To your second point, with regards to this "custom aggregating connector" you mention, what you are describing there is actually the work of the query engine itself! Because we already have the Trino query engine executing these operations on the data returned from our connectors, there is nothing gained from trying to add a new layer that does these operations. The correct path forward for enhanced performance on things that you may be considering burdensome is to enhance our ability to push down operations and filters to our connectors and reduce data scanned, thereby alleviating some burden on the query engine itself. Adding a uber-connector to do this work is not the right path.

I'm going to close this out as we don't see the value in this connector-of-connectors proposal. Feel free to re-open and explain more if you disagree.

**Comment by hackett123** [comment]
Hi @rgibbard ,

Thanks for explaining your concept more. Your idea to simplify and dynamically produce virtual tables sounds interesting, and is actually something similar to what we already do for the CMDB connector in order to create virtual tables of things like customer EC2 instance information, etc. So I would be interested in seeing more of what you're thinking about there - you mentioned implementing a variation of one of the existing connectors for your particular use case, so I would encourage you to raise a PR for it if you feel it has value we can extract across multiple connectors once we can see it in action.

Regarding the query-rewrite idea, this is not actually feasible because as the connectors process splits, they are not aware of the full query. The connector essentially processes different subqueries until the full query from Trino is complete. So if we tried to do a query-rewrite on the input to the connector, we wouldn't actually be able to do anything useful.

**Comment by rgibbard** [comment]
@hackett123 
Ok, i’ll have a look at the CMDB connector and see if I can follow its lead. Thanks!
