### ISSUE TITLE
[BUG] Make prepare_dev_env.sh to support Ubuntu

### ISSUE THREAD

**Issue by henrywu2019** [awslabs/aws-athena-query-federation#150]
**Is your feature request related to a problem? If yes, please describe.**
Yes

**Describe the solution you'd like**
Use apt instead of yum

**Describe alternatives you've considered**
NA

**Comment by hackett123** [comment]
`prepare_dev_env.sh` is meant for mac users. For Linux users, we recommend following this setup https://github.com/awslabs/aws-athena-query-federation/wiki/Building-aws-athena-query-federation-using-container_env which will create a docker image for you to use for development in our repository. This is the cleanest approach because you will be sure to have the correct versions of java, maven, the github cli, the sam cli, and the aws cli. It will also avoid any conflicts with your other maven projects as it will have its own dedicated m2 repo. Happy coding!
