### ISSUE TITLE
[Feature Request] add support for UUID, JSON etc with connector athena-jdbc

### ISSUE THREAD

**Issue by henrywu2019** [awslabs/aws-athena-query-federation#153]
**Describe the bug**
athena-jdbc doesn't support type of UUID, JSON...which are supported in PostgreSQL

**To Reproduce**
 - Create a connector which connects to PostgreSQL with a table having columns of UUID, JSON etc
- In Athena web console, you cannot see the table, and you cannot query at all.

**Expected behavior**
I can see the table and query.

**Comment by avirtuos** [comment]
Please be specific about which types you'd liked supported. Not all Postgres types are supported in Athena so some types will require coercion. Your request will have a high chance of being prioritized if it contains specific details about your need. For example, are their any types which you need urgently vs the entire type population of postgres?

**Comment by henrywu2019** [comment]
We need UUID and timstamp supported. And UUID is primary key in some tables. Thanks a lot.

**Comment by apprithm** [comment]
I encountered the same issue today.
I also have some tables were using UUID and timestamp,  the athena-jdbc-connector will fail to map those columns.

**Comment by pvieito** [comment]
We also would like UUID and JSONB support from PostgreSQL (both could be coerced to VARCHAR).

**Comment by jiamo** [comment]
In one database have many tables. But even we want join a table without uuid. It still failed , seem it parse all table field?

**Comment by timneedham** [comment]
Hi,

**Any progress with this at all?** :worried: 

We've got `uuid`  and `timestamp with time zone` columns in all tables throughout our Postgres database, and those fields fail to appear in Athena. Other Postgres-specific features (like arrays, composite-type columns etc.) appear to stop _any_ table from appearing in Athena.

Athena is a great fit for our use case... but this lack of driver support is proving a real barrier... especially the lack of  timestamp mapping. The best that seems possible is `postgres_timestamp_column::date`... but that loses the time portion.

Similarily, `some_postgres_uuid_column::text` works... but maintaining that via a view (and potentially missing the indexes) is a high cost to incur.

> @avirtuos : Please be specific about which types you'd liked supported

For us:

*  `uuid` (even if it just maps to a string?)
* `timestamp with time zone`
*  PostgreSQL array support

Not sure if this is relevant here, but PostgreSQL columns > 30 characters are truncated too, which is causing some issues.

**Any feedback/possible timescales would be very much appreciated!**

**Comment by avirtuos** [comment]
We have not yet started on this item. If this is a high priority for you, one suggestion I can make for expediting is to speak with your account team to escalate. I'll do my best to get this prioritized regardless.

**Comment by shurvitz** [comment]
I'm currently working on adding PostGreSQL array support. timestamp is already supported: #314, but not sure about timestamp w/tz.

**Comment by avirtuos** [comment]
@shurvitz , @soojinj can show you about tz work she did recently which might help.

**Comment by shurvitz** [comment]
#319 adds support for PostGreSQL ARRAY type. Will look at uuid and timestamptz next.

**Comment by timneedham** [comment]
Oh wow, thanks all! :hug:
I'll let you know once it's merged...

Thanks for such a quick response, very much appreciated!

**Comment by shurvitz** [comment]
FYI, I just cut a new release for Athena Query Federation (v2020.51.1) and published to SAR in prod. This release includes all the latest PRs including #319. 
Let me know if it addresses your issue so that I can close it.

**Comment by shurvitz** [comment]
@timneedham Any update on testing the fix?

**Comment by timneedham** [comment]
Hi @shurvitz ,

**Sorry for the delay.**

We are using the latest version now for development, and the immediate issue we had with numeric columns has certainly been fixed. We'll be getting back into it next week and should be able to report back more thoroughly soon.

But looking good so far, thanks again!

**Comment by shurvitz** [comment]
Hi @timneedham. Checking in to see if this issue is resolved.

**Comment by timneedham** [comment]
Hi @shurvitz ,

**It looks great!** :pray: 

**Here's a summary of our column data-types which previously failed, and now work:**

| Previously failing Column Type | Athena type, since fix|
| ---------------- | ---------------- |
| `uuid` | `varchar` |
| `character varying[]` | `array<varchar>` |
| `character varying[]` | `array<varchar>` |
| `timestamp with time zone` | decimal(9,6) |
| `numeric(9,6)` | timestamp |
| `jsonb` | varchar (valid JSON string :+1:) |
| `geography` (PostGIS) | varchar |
| Custom types | varchar | 

...so this is great news (thanks for all you help!), and it gets us a long way towards where we wanted to be.

**The only (really) small thing I can see now is arrays of custom types?**

As above, a custom type (for example we have `bookmark` which contains URL, alt-text, title columns etc.) work fine for a single column - they get cast to a `varchar` in Athena, which is totally workable:

`(https://amazon.com,Amazon)` (varchar)

...however **_arrays_** of `bookmark` aren't cast as `array<varchar>`, as might be expected, they're instead flattened as a single `varchar` too:

```
{"(https://amazon.com,Amazon)","(https://google.com,Google)"}
```

...this certainly ins't a show-stopper, but it's a little inconsistant to apply array-splitting in these instances, and not if the datatype isn't a composite type?

**I'm more than happy this issue can be closed though, thanks again and apologies for the delays in getting this back to you.**

**Comment by shurvitz** [comment]
@timneedham, glad to hear things are working much better now. As far as the composite array issue you describe, I would need more information on how it was constructed in order to try and recreate the issue here (e.g. create type...).

When I tried to recreate the issue here it seemed to work okay:

**Comment by shurvitz** [comment]
@timneedham, glad to hear things are working much better now. As far as the composite array issue you describe, I would need more information on how it was constructed in order to try and recreate the issue here (e.g. create type...).

When I tried to recreate the issue here it seemed to work okay:

```
postgres=> create type info as (first_name varchar, last_name varchar, birthday date);
CREATE TYPE

postgres=> create table registry (id integer, family info[]);
CREATE TABLE

postgres=> insert into registry values (1, ARRAY[ROW('Joe', 'Schmoe', date('2001-05-15'))::info, ROW('Jane', 'Schmoe', date('2003-03-13'))::info]);
INSERT 0 1
postgres=> insert into registry values (2, ARRAY[ROW('John', 'Doe', date('2000-07-17'))::info, ROW('Jane', 'Doe', date('2005-02-27'))::info]);
INSERT 0 1

postgres=> select * from registry;
 id |                         family                         
----+--------------------------------------------------------
  1 | {"(Joe,Schmoe,2001-05-15)","(Jane,Schmoe,2003-03-13)"}
  2 | {"(John,Doe,2000-07-17)","(Jane,Doe,2005-02-27)"}
(2 rows)
```

In Athena `family` is listed as `array<varchar>` and the following query works:

**Comment by rafiron** [comment]
Hi @shurvitz,

Using the athena-jdbc connector when I'm querying a uuid field, I'm getting this error 

```
0: ERROR: operator does not exist: uuid = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 197
```

Here's a sample query that I'm firing

```sql
SELECT * FROM <db>.<schema>.<table> where <uuid column> = 'some uuid';
```

I can see that the table schema shows my column of type `uuid` as `varchar` but when I'm performing a where clause on that I'm getting this issue and from the looks of it, it seems that athena is attempting to pass the uuid value as varchar which causes issues on postgres side.

Is there any way I can get this query working ?

**Comment by shurvitz** [comment]
Hi @rafiron,
you can try casting your uuid field to varchar in the predicate. I'm no longer with Athena, but you can direct specific questions to @burhan94

**Comment by rafiron** [comment]
@shurvitz can you tell how the query should look like in this scenario.
@burhan94 can you kindly help me with this issue.
