### ISSUE TITLE
[BUG] A potential risk in the AthenaDynamoDBConnector which can be used to leak sensitive data.

### ISSUE THREAD

**Issue by zolaer9527** [awslabs/aws-athena-query-federation#1570]
**Summary**
Hello! I found a potential risk in the AthenaDynamoDBConnector when I deployed it in the AWS Serverless Application Repository. It can leverage "s3:ListAllMyBuckets" to list all buckets in the account, such as the buckets created by other applications in the serverless repo. Then it can leverage "s3:GetObject" to get all objects in all buckets. Therefore, a malicious user can use the AthenaDynamoDBConnector to obtain all data in S3, eventually leading to information leakage.

**Describe the bug**

Before the AthenaDynamoDBConnector was deployed, it needed a parameter called SpillBucket, which is an S3 bucket to spill data. However, I found that I could construct the name of a bucket that didn't exist, even *, which caused the permissions of the IAM role assigned to the application to be escalated. In the design, the permission "s3:GetObject" just can only get the object in the SpillBucket. But a malicious user can use * as the SpillBucket so that he can leverage the permission "s3:ListAllMyBuckets" and "s3:GetObject" to get all objects in all buckets.

**To Reproduce**
During the deployment of the AthenaDynamoDBConnector application, I inputted "*" as the parameter of SpillBucket. After that, I executed the following command in Cloudshell.
1. aws sts assume-role --role-arn "arn:aws:iam::747955086145:role/serverlessrepo-AthenaDynamoDBConnecto-FunctionRole-17FATA7YVJ1U2" --role-session-name CLISession
2. Then I exported AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN  from the echo result into the environment variable and switched users.
3. Finally, I verified my current identity and obtained all the content in all s3 buckets.

**Expected behavior**
The role should just have the CRUD permission for the specified S3 Buckets.

**Screenshots / Exceptions / Errors**
![picture-1 ](https://github.com/awslabs/aws-athena-query-federation/assets/103011488/8ad86afc-3636-4886-a445-e6ea01538835)
![picture-2](https://github.com/awslabs/aws-athena-query-federation/assets/103011488/a6b134c0-0335-4d32-bc4b-33710430b546)

**Connector Details (please complete the following information):**
 - Version: 2023.42.1
 - Name:dynamodb

**Mitigation Discussion**

1. The parameter which is the name of the S3 Bucket should be checked before the application is deployed. It must ensure that the Bucket exists and filters illegal parameters.
2. The permission "s3:ListAllMyBuckets" should be removed if it will not affect the normal functionality.

**Question**

1. Is it a real issue in the AthenaDynamoDBConnector?
2. If it's a real issue, can any of my suggestions be used to solve this problem?
3. If my suggestions can be used to solve the problem, can you give me a CVE?
```[tasklist]
### Tasks
```

**Comment by akuzin1** [comment]
Federated Connectors are supposed to be light weight applications that the customer can deploy into their account, with minimal overhead. By design, Athena has a shared responsibility model with the customer; Athena provides a template to automate the creation of necessary resources through SAR, with principle of least privilege. Since these are resources that are deployed in the customer's accounts, it's the customer's responsibility to ensure that their resources are adequately secured according to the policies set by their organization or administrators. Addressing your concern the role created by the application can only be assumed by the AWS Lambda service, defined through trust relationships of the role, which must have been altered to allow the role to be assumed by your AWS user, which would be identifying a gap on the account admins behalf.
