### ISSUE TITLE
[BUG]  reserved keyword: name in DynamoDB Connector

### ISSUE THREAD

**Issue by mhmdbahja** [awslabs/aws-athena-query-federation#158]
I configure everything correctly but when I try to run the following query  : 

select name,age FROM "test-table"

This error appears in Athena : 

Your query has the following error(s)
SYNTAX_ERROR: line 1:28: Column 'name' cannot be resolved
This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: 19ed9447-adbc-4e92-98ad-81e75db0842c.

After looking in cloudwatch of the connector lambda this errors appears : 

Invalid ProjectionExpression: Attribute name is a reserved keyword; reserved keyword: name(Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 0DC9L9943FONT8EH73VSOKJ1PJVV4KQNSO5AEMVJF66Q9ASUAAJG): 

It looks like I need to configure something like ExpressionAttributeNames in dynamoDB query

**Comment by atennak1** [comment]
This was fixed with https://github.com/awslabs/aws-athena-query-federation/commit/3d043ffd1f5a8a6050a785a00292f7eb56429e9f and will be included in the next release.  You can follow [this](https://github.com/awslabs/aws-athena-query-federation/wiki/How_To_Build_A_Connector_or_UDF#upgrading) to deploy the fix before then
