### ISSUE TITLE
[FEATURE] Oracle JDBC Support

### ISSUE THREAD

**Issue by bknorr001** [awslabs/aws-athena-query-federation#170]
Oracle JDBC support to provide broader coverage of relational databases as well as hybrid deployments using privatelink.

**Comment by avirtuos** [comment]
Hi @bknorr001 , thank you for your request. Oracle support is certainly on our radar and isnt yet released while we figure out the licensing for the driver and if/how we'd provide the 1-click deploy experience we have with the other connectors you see in this repository. We will update this request as we get closer to a solution.

As for the second part of your question, can you elaborate on how specifically you envision private link coming into play? I ask because while we plan to support runtimes other than Lambda in the future, the current model does rely on Lambda which means you can use any network topology you see fit to connect from Lambda to your database server(s).

I'll post a similar response on your other feature request for MS SQL.

**Comment by bknorr001** [comment]
Thanks for taking a look @avirtuos. Hopefully, I didn't confuse things too much with my privatelink comment, but the use case I was trying to convey is adding the ability for Query Federation to connect to commercially licensed databases like Oracle and MS SQL on customer premise.

**Comment by avirtuos** [comment]
That makes sense. The location of the database will not matter as long as your lambda function has network connectivity (and likely DNS resolution of) your intended target.

**Comment by dustinfarris** [comment]
Does anyone know if there's an open source connector out there for Oracle?

**Comment by henrymai** [comment]
Available now: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-oracle
