### ISSUE TITLE
[FEATURE] MS SQL JDBC Support

### ISSUE THREAD

**Issue by bknorr001** [awslabs/aws-athena-query-federation#171]
Microsoft SQL Server JDBC support to provide broader coverage of relational databases as well as hybrid deployments using privatelink.

**Comment by avirtuos** [comment]
Hi @bknorr001 , thank you for your request. Oracle support is certainly on our radar and isnt yet released while we figure out the licensing for the driver and if/how we'd provide the 1-click deploy experience we have with the other connectors you see in this repository. We will update this request as we get closer to a solution.

As for the second part of your question, can you elaborate on how specifically you envision private link coming into play? I ask because while we plan to support runtimes other than Lambda in the future, the current model does rely on Lambda which means you can use any network topology you see fit to connect from Lambda to your database server(s).

I'll post a similar response on your other feature request for MS SQL.

**Comment by AndrewHannigan** [comment]
+1 specifically for 1-click deploy of Microsoft SQL Server JDBC connector, I would definitely make use of this.

**Comment by chadmorrow** [comment]
I've tried working this one out myself but haven't gotten anywhere with it. I do have a first born child I can trade for someone else's time and effort to get this made though ;)

**Comment by weiwarren** [comment]
+1

**Comment by nrouhanizdeh** [comment]
+1

**Comment by henrymai** [comment]
SQL Server connector has been available since April 21st 2022
