### ISSUE TITLE
[QUESTION] AthenaDynamoDBConnector Update AWS version

### ISSUE THREAD

**Issue by kikemarto** [awslabs/aws-athena-query-federation#247]
Hi guys, I have a question.

In "AthenaDynamoDBConnector" is with the version version 2020.33.1

![image](https://user-images.githubusercontent.com/14853156/93103009-61923100-f6ac-11ea-8a9b-6347956c9380.png)

But in this repo is with a newer version.

https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/athena-dynamodb.yaml

![image](https://user-images.githubusercontent.com/14853156/93103102-838bb380-f6ac-11ea-9b6f-7556610e1dec.png)

I use the easy way with serverlessrepo, how update?

Regards

**Comment by shurvitz** [comment]
Hi @kikemarto, 2020.33.1 is the Release version that is currently deployed in production. So if you try to add a connector via the Athena console, that is the version of the connector that will be used.

The repository, however, has a more recent version for two reasons:
1. More changes were introduced to the Repo since the release: https://github.com/awslabs/aws-athena-query-federation/compare/v2020.33.1...master
2. The working semantic version needs to be always higher than the one in production, so when you build a connector locally, you can publish it without any issues.

**Comment by shurvitz** [comment]
You can build the connector locally to incorporate recent changes: https://github.com/awslabs/aws-athena-query-federation/wiki/How_To_Build_A_Connector_or_UDF#upgrading

**Comment by kikemarto** [comment]
Thank you @shurvitz !!!
