### ISSUE TITLE
[BUG] Athena  Queries  return incorrect result for dynamodb table having different data struct in same attribute

### ISSUE THREAD

**Issue by aartihbhange** [awslabs/aws-athena-query-federation#256]
It seems DynamoDBConnector for Athena do not infer the schema properly for dynamodb table . This  is happening when dynamodb items contains different array-of-struct type data in same attribute. We tried using and avoiding Glue crawler for schema inference. It give incorrect results while using Glue table schema. The connector infers schema for only first record/item in dynamodb attributes and uses same schema for this attribute in all other items.

To Reproduce
1. Create a table in DynamoDB with same pk and different sk , and different listof structs values in attribute 'data'.
2. First item 'data' attribute should have struct of strings - 
pk=11, sk=userdata, data ={name='abc', jobid='mn_03',businessunit='0018'}
3. Second item 'data' attribute should have struct of arrays - 
pk=11, sk=assignment , data = {name='abc', starunits=[{value='str_01' , percentage='25'}, {value='str_08', percentage='75'}] , updateby='user.test'}
4. create a datasource in Athena using dynamodbconnector.
5. run query select * from datasource.default.dynamodbtablename where pk='11'.
6. result contain two records but the nested fields from 'data' attribute are fetched for first item only and are ignored for 2nd item
eg.
pk    sk                   name    jobid     businessunit
11   userdata           abc       mn_03    0018
11   assignment       abc        null        null

Expected behavior
The query should be executed successfully and should infer schema for all nested fields in all columns/attributes.

its a common dynamodb use case to store different json structure in same attribute in different items.

I tried using Glue crawler to infer the schema for this dynamodb table and the athena query returns null values for all fields in 'data' attribute for both the items.
 
DynamoDBConnector version 2020.33.1

**Comment by avirtuos** [comment]
@aartihbhange You are highlighting a key challenge with how Athena makes use of schema. Essentially, Athena needs to know the schema of the table it is reading 'up front'...at what we call query planning time. In addition to the timing concerns (e.g. determining schema needs to be 'fast' in order to avoid impacting performance), it also means that the schema of the table needs to be a superset of the schema of all rows. Our schema inference feature works well for many use cases but is a poor substitute for true schema-on-read, which is what your example really requires. schema-on-read essentially allows the schema of each record to vary and as such, no real up-front schema is needed. There are some cases where your example would work today, namely if the values for a field can be coerced into a single type. For example, if your data field had values of "Hello" and 123.10... those could both be coerced to a String, which while not ideal does give you some more flexibility in your query to do casting and/or filtering for the values you care about.

But today, the only option for what you described is to try and define the schema, as a superset of all possible value types, in Data Catalog.


@atennak1 can you keep me honest on the above, you're most familiar with the DDB connector.
