### ISSUE TITLE
[FEATURE] [QUESTION] DynamoDB connector - targeting a cross-account Glue catalog

### ISSUE THREAD

**Issue by tudor-a** [awslabs/aws-athena-query-federation#292]
I have a question that's related to a new feature. It is related to one of the DynamoDB Connector features mentioned in the Readme file, that says:

`glue_catalog - (Optional) Can be used to target a cross-account Glue catalog. By default the connector will attempt to get metadata from its own Glue account.`

I've searched through the entire dynamodb repo for more clues, I looked into the commits and I've found no further mentions, or instructions on  how to use this functionality. Is this achieved separately from the deployment of the connector, by adding necessary IAM permissions (e.g. for Glue), or are there any other AWS services that need to be included to achieve this?
Thank you

**Comment by avirtuos** [comment]
@tudor-a The value you place in that Lambda env variable will be used to determine which Glue catalog the connector uses. Can you help me understand your specific question? what are you trying to do and what part are you stuck on? I agree that the documentation could be clearer. We'll work on that.

**Comment by tudor-a** [comment]
Hello @avirtuos, thanks for the feedback!
What I don't understand is, do I need to deploy other resources except DynamoDB connector to enable  access to a cross-account Glue catalog?
I currently only deploy the standard DynamoDB Connector, and I tested adding cross-account roles that would enable Athena access to a dynamodb connector lambda function from a different account. (My guess is that I've taken a wrong approach to this).

After researching other repos here I found this: https://github.com/awslabs/amazon-athena-cross-account-catalog. Do I need to deploy the Amazon Athena Cross Account Data Catalog as well to enable what I need?

> @tudor-a **The value you place in that Lambda env variable will be used to determine which Glue catalog the connector uses.** Can you help me understand your specific question? what are you trying to do and what part are you stuck on? I agree that the documentation could be clearer. We'll work on that.

I'm trying to enable access to a Glue catalog in account B by running an Athena query with a DynamoDB Connector in account A.
1. Can you explain what do you mean by "the value in that Lambda env variable will be used to determine which Glue catalog the connector uses"? What type of value should this be?
2. Also - if I specify a different Glue catalog (the one from another account) does it mean that this DynamoDB Connector can be used only to target the Glue catalog from the other account?
3. Regarding IAM policies, my guess is that IAM policies are necessary to access the cross-account glue data catalog and the target S3 bucket?

Any feedback on **the steps necessary to establish targeting a cross-account Glue catalog using the DynamoDB Connector** would be very welcome!
I apologize for so many questions, I hope perhaps these questions might turn out useful for future documentation updates.
Thanks

**Comment by tudor-a** [comment]
Hello @avirtuos ,
here's a new update. I added the account number in the "glue_catalog" env variable of the Lambda, and I managed to setup crossaccount access to the glue catalog.
Now, I can list the Glue tables from the other account with: `show tables in `lambda:<name>`.default` 

But I still cannot query that dynamodb table, i keep getting the ResourceNotFound Exception.
Can you explain how to setup policies (and which policies) to enable crossaccount access to dynamodb? Can this Lambda function assume role from another account? (I've tried to set this up as well, but I keep getting the same ResourceNotFound exception.

Any feedback would be welcome!
Thanks

**Comment by sivankumar86** [comment]
It seems, connector does not support cross account dynamodb access. 

https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java#L114

**Comment by hackett123** [comment]
Here is a description of today's behavior:

For metadata, the connector will attempt to reference the Glue metadata for whatever account was given in the `glue_catalog` environment variable. Suppose I have my connector deployed in account A and I have my Glue metadata in account B. In account A, I deploy the DynamoDB connector, and add the environment variable glue_catalog with value B (this would really be the 12 digit account id). When I run a query such as `show schemas`, I will fetch the metadata from account B so long as the proper trust relationships exist between the two accounts. This means that account B modifies their data catalog settings to grant permissions to allow the function execution role that the Lambda uses to access the catalog/db/table in account B, and in account A, you add a policy to the function execution role that allows glue:* against those resources.

Then, for fetching rows, the behavior is to look at a dynamodb table only within account A. So, the only situation where cross-account data catalog works is if the dynamodb table exists in account A. However, if the table exists in account B (alongside the data catalog), then fetching the rows will fail, as the connector today will not look across accounts for the actual DDB requests.

I have validated all of the above behavior.

In order to allow cross-account dynamodb requests, there is a code change required, as well as additional permissions configured by the user. This is discussed here https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/configure-cross-account-access-to-amazon-dynamodb.html, but the changes summarized would be (please note that the article uses A and B in opposite meanings of what I've described here):
- Account B adds a role with permissions to query/scan a DynamoDB table, and adds account A's account id as a trusted entity
- Account A adds a policy that allows it to assume the above role in account B
- Account A adds this new policy to their function execution role

What I will do is add functionality for the connector to take in a new environment variable with the cross-account role arn to assume when reading from DDB and have the lambda assume that role before making DDB requests. And I will link the PR once it is created.

**Comment by hackett123** [comment]
Feature has been added via PR https://github.com/awslabs/aws-athena-query-federation/pull/1179, and will be available in the next release. If anybody needs this BEFORE the next release, you can just build the repo and upload the ddb jar to your lambda. Otherwise we will have a release sometime in the next week.
