### ISSUE TITLE
[BUG] field partition_schema_name not found with postgres connector

### ISSUE THREAD

**Issue by eddiesiegel** [awslabs/aws-athena-query-federation#327]
**Description**
We have a very vanilla connection to postgres without anything unusual going on. Everything was working fine until recently (a couple of days ago?). Now when we query any of our postgres tables, we get an error that looks like this:

`GENERIC_USER_ERROR: Encountered an exception[java.lang.IllegalArgumentException] from your LambdaFunction[arn:aws:lambda:us-west-2:xxxxxxxxxxxx:function:athena-postgres-connection-v2] executed in context[retrieving meta-data] with message[field partition_schema_name not found in [id: Int(64, true)]]`

Some debugging information:

This query triggers the error:
```sql
SELECT id FROM postgres.myschema.mytable LIMIT 1;
```

These queries do not:
```sql
SELECT * FROM postgres.myschema.mytable LIMIT 1;

SELECT id, partition_schema_name, partition_name FROM postgres.myschema.mytable LIMIT 1;
```

I tried deploying a new copy of the lambda function in case that would provide any updated code, but we are still seeing the same behavior.

**Connector Details:**
 - Version: 2020.51.1
 - Name: postgres
 - Athena Query IDs: 611cf373-8258-4222-97a0-9409ae43cfaa

**Comment by shurvitz** [comment]
@eddiesiegel Sorry you're having issues with this connector. Did the issue start before you upgraded to v2020.51.1?
Can you also share the CloudWatch logs and the table schema (w/sample data if possible). I'd like to try and recreate the issue here.

**Comment by shurvitz** [comment]
@eddiesiegel I've just confirmed that there is a change that hasn't made it to the preview pool yet. Since you are using workgroup: `AmazonAthenaPreviewFunctionality`, all queries are directed to the preview pool. I would suggest creating/using a workgroup that is mapped to `Athena engine version 2` and using that instead (see https://docs.aws.amazon.com/athena/latest/ug/engine-versions.html)

Let me know if that resolves the issue.

**Comment by eddiesiegel** [comment]
Yes, that appears to have resolved the issue. Thank you for the prompt response!
