### ISSUE TITLE
[FEATURE] Backquotes support

### ISSUE THREAD

**Issue by QuanticPotatoes** [awslabs/aws-athena-query-federation#369]
Hi,
The backquotes doesn't seem to work with the JDBC MySQL connector. The only solution to select data from a table containing uppercase characters was to create a view with no uppercase characters in the table name.
Will it be supported in the next release ?

The table is correctly listed :
![image](https://user-images.githubusercontent.com/7420853/110803275-509f3280-827f-11eb-8712-bc6b3f0974ed.png)

By nothing happens with the query :
![image](https://user-images.githubusercontent.com/7420853/110802353-66f8be80-827e-11eb-8a82-9124413c975d.png)

Version :`AthenaJdbcConnector — version 2021.6.1`.

**Comment by avirtuos** [comment]
The SQL grammar is not dictated by the connector, the behavior you are observing is because Athena does not support back-ticks in that way. You should use single quotes for tables, column, databases and double quotes for literal values. Also, keep in mind that Athena does not support case sensitive table names. Some connectors try to work around this by doing a case insensitive table search to re-write your query but that is really not a full solution.
