### ISSUE TITLE
[QUESTION] General question DynamoDB connector using GSI

### ISSUE THREAD

**Issue by laurihak** [awslabs/aws-athena-query-federation#372]
I have a question that I don't think is related to a bug or feature request. 

So can i force to query GSI on athena? I did not see documentation for adding parameter with query to put index name?
I am asking if it is possible to do it straight in SQL or do i need to modify the lambda?

**Comment by atennak1** [comment]
I don't believe you can force a GSI at this time.  In terms of using one, no extra parameters are necessary.  The connector will automatically discover GSIs/LSIs and use one only if it results in more optimal DDB requests (e.g. Queries instead of Scans) based on the predicates in the WHERE clause, and only if the all the required columns are projected (surfaced) by the GSI/LSI.

**Comment by laurihak** [comment]
Yeah, seems to be working great!
