### ISSUE TITLE
[QUESTION] RecordHandler Serialization Exception when Spilling Records

### ISSUE THREAD

**Issue by teddyf** [awslabs/aws-athena-query-federation#455]
While running queries against "larger" fields, we are getting the following exception from the recordhandler (we are running a custom connector which extends both record/metadata handler). 

Your query has the following errors:GENERIC_INTERNAL_ERROR: Encountered an exception from LambdaFunction[arn:aws:lambda:us-east-1:accountnumber:function:functionName] executed in context[S3SpillLocation{bucket='spill-bucket-name', key='hash/id/id', directory=true}] with message[Expected START_OBJECT found null]

There are no failures in the recordhandlers and no logs that expose any insight on this issue. Is this a known issue when querying against larger fields?

**Comment by avirtuos** [comment]
This is not a known issue. Can you share query ids and region where you encountered this?

**Comment by teddyf** [comment]
queryId: 52dddc3f-13e6-4903-8668-df6640d31a38
region: us-east-1

**Comment by hackett123** [comment]
We haven't heard any instances of this issue since the ticket opening (22 months ago). With that lack of data, the age of the ticket, and the fact that this is a custom connector, we have no information suggesting we can investigate this or that the issue persists. Therefore I am closing it out, but if any customer has a similar issue please reopen.
