### ISSUE TITLE
Error while deploy DynamoDB connector manually

### ISSUE THREAD

**Issue by saadmsheikh** [awslabs/aws-athena-query-federation#457]
I am trying to deploy the DynamoDB connector manually using the steps mentioned in https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#deploying-the-connector, but I am getting errors below:

"Caused by: java.lang.UnsupportedClassVersionError: org/apache/maven/plugins/checkstyle/CheckstyleViolationCheckMojo : Unsupported major.minor version 52.0"

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project aws-athena-federation-sdk: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check failed: Unable to load the mojo 'check' in the plugin 'org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/apache/maven/plugins/checkstyle/CheckstyleViolationCheckMojo : Unsupported major.minor version 52.0

**Comment by avirtuos** [comment]
What step of the deployment process are you on when you get this error
message? Put another way, what command did you (or the publish script) run
when receiving this error?

Also, what java version are you using? This error typically occurs when you
have a java version that is not supported by one or more maven plugins.
maven is what builds the connector.

Alternatively, you can install the DDab connector from a pre-built copy
Athena maintains in Serverless Application Repository.

**Comment by saadsheikhaws** [comment]
So I was able to dig deep and google my way through this issue. As you said, openjdk version was not compatible alongwith Maven too. So I updated both to 1.8 and 3.8 and it worked flawlessly afterwards. The reason I can't use the SAR template, is because I have to add a role permission boundary in the template, due to organization policy. So I have to manually pass the S3 bucket and Key in the template.

It is now working and I have deployed the template. Thanks for your help.
