### ISSUE TITLE
[QUESTION] Cloudwatch Logs Connector Throttling

### ISSUE THREAD

**Issue by seancarr26** [awslabs/aws-athena-query-federation#466]
Hi,
    I am using the connector to retrieve some API Gateway Cloudwatch logs for 24 hour periods. 
The API Gateway Cloudwatch logs can update 1000s of different log streams in a 24 hour period. The connector seems to attempt to retrieve data from all of these log streams in parallel, causing a huge amount of Logs Throttling Exceptions from Cloudwatch and eventually resulting in the query timing out.
I have tried a number of different settings for the environment variables:

- throttle_decrease_factor
- throttle_increase_ms 
- throttle_initial_delay_ms 
- throttle_max_delay_ms

but the impact is minimal.
Have tried reducing the concurrency settings for the Connector Lambda (reducing to 10 or 100 etc), but then get lots of Lambda Throttling errors and the query seems to abort.

I was wondering if there is anyway to reduce the parallelism of the log stream processing i.e. instead of trying to process all logs streams at once, to only process a max of N log streams at a time.

**Comment by avirtuos** [comment]
It sounds like you've tried everything I would expect. I'm surprised that reducing the Lambda concurrency didn't work. That just seems wrong. Can you elaborate on what exactly happens if you set the Lambda concurrency to something low like 2? An Athena query id and some logs from your Connector would also help pinpoint the issue. 

The way this shoudl work is that if you reduce the number of concurrent Lambdas, the query just gets slower. Now that might result in you reaching your max Athena query runtime limit but thats a soft limit and we can increase it in many cases.

Another thing to be aware of, though it may not be helpful to you right now unless we make some changes to the connector. Can you query a specific log stream and see if that also has the same issue? That is another way to limit parallelism, though it may not be what you want since that limits the data being read as well.

**Comment by seancarr26** [comment]
When I set concurrency to 2, the query fails in Athena with the following error message

> GENERIC_USER_ERROR: Query encountered too many throttles while calling your Lambda function

Querying a single Log Stream works fine. 
Thanks.

**Comment by hackett123** [comment]
Given the conversation between Anthony and seancarr26@, there does not seem to be any further recommendations to give or actions to take by the customer. It is a well known limitation that the CloudWatch API is particularly prone to throttling. Unfortunately, the best the customer can do is query fewer log groups at a time to avoid this throttling. I will close out the ticket.
