### ISSUE TITLE
[BUG] Cannot set different log level for "com.amazonaws.athena.connectors.dynamodb"

### ISSUE THREAD

**Issue by gcobr** [awslabs/aws-athena-query-federation#493]
The file [athena-dynamodb/src/main/resources/log4j2.xml](/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb/src/main/resources/log4j2.xml) contains:
```
<Logger name="com.amazonaws.athena.connector.lambda" level="${env:ATHENA_FEDERATION_SDK_LOG_LEVEL:-warn}" />
```

This allows me to change the log level for `com.amazonaws.athena.connector.lambda` by setting the environment variable `ATHENA_FEDERATION_SDK_LOG_LEVEL` to something else (info, error, debug) in the Lambda settings.

However, the classes in the `athena-dynamodb` module emit logs through `com.amazonaws.athena.connectors.dynamodb`. See [this](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java#L301) an example.

There is no simple way to change the log level for that logger without repackaging and redeploying the Lambda Function.

In the absence of a placeholder variable in log4j2.xml, it will default to the root logger which is hard coded for the `warn` level only:

```
<Root level="warn">
   <AppenderRef ref="Lambda" />
</Root>
```

How can I change the log level for `com.amazonaws.athena.connectors.dynamodb` without repackaging and redeploying?

**Comment by janmran** [comment]
This looks to be a bug due to guard [here](https://github.com/awslabs/aws-athena-query-federation/blob/7ecdbadf46d9d8d6c1a6f913a38db2bd2bba2051/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java#L300)
Unguarded log statements from the same class are still visible in the logs. Unfortunately is looks like a redeployment is necessary once the the fix is available.

**Comment by janmran** [comment]
#496 should address the logging issue. A redeploy from the master branch will be required
