### ISSUE TITLE
[BUG] Empty result when using Athena UDF with return value java.util.Map

### ISSUE THREAD

**Issue by janborch** [awslabs/aws-athena-query-federation#512]
**Describe the bug**
Lambda UDF with  a return type of java.util.Map<String,Object> return `{field0=null}` instead of the JAva Map content.

**To Reproduce**
Deploy the following Lambda UDF

```
public class TestUDF extends UserDefinedFunctionHandler {
   private static final String SOURCE_TYPE = "AWS";
   public TestUDF() {
        super(SOURCE_TYPE);
   }

    public Map<String, Object> getmap(String key, String value) {
        Map<String, Object> map = new HashMap<>();
        map.put(key, value);
        return map;
    }
}
```

I call the function using the following Athena query:

```
USING EXTERNAL FUNCTION getmap(key VARCHAR, value VARCHAR) RETURNS ROW(VARCHAR) LAMBDA 'test-UDFFunction'
SELECT getmap('key','value') as test
```

I'm expecting a return value: 
`{key=value}`
but I get 
`{field0=null}`

Do you have guidance on how to create an Athena UDF returning ROW/Map?

**Connector Details (please complete the following information):**
 - Version: 2021.42.1 from maven repo
 - Name: custom UDF
 - Athena Query ID : fb410650-d220-4e75-af26-a8e4472fb5ab eu-west-1

**Comment by sbrandtb** [comment]
I think you need to advertise the actual schema of the row to Athena. So instead of `RETURNS ROW(VARCHAR)`, `RETURNS ROW(a VARCHAR, b VARCHAR)`. A [row](https://prestodb.io/docs/current/language/types.html#row) in PrestoDB/Athena is actually a struct in the hive world, meaning it got a fixed schema. What you are trying to return looks more like a [map](https://prestodb.io/docs/current/language/types.html#map), which is a mapping from string to an arbitrary object type. [The documentation](https://docs.aws.amazon.com/athena/latest/ug/querying-udf.html#udf-query-syntax) does not mention the possibility to return maps.

**Comment by sbrandtb** [comment]
See also #361

**Comment by bryan-jamf** [comment]
@sbrandtb I'm experiencing the same issue.  Basically I'm returning a java.util.Map<String, Object>, but in Athena the result is {key1=null, key2=null}, etc.  If I return in a different format (serialize to json for example) then the values are there as expected.

Also, the documentation that you linked to does reference that java.util.Map should map to a `ROW` type in prestodb.

**Comment by bryan-jamf** [comment]
Update: this worked for me by matching the variable names properly from the invocation to the advertisement of the schema mentioned a couple comments up.

**Comment by ykrystal** [comment]
[Please see comment above.](https://github.com/awslabs/aws-athena-query-federation/issues/512#issuecomment-988046857)
