### ISSUE TITLE
DynamoDB to QuickSight issue

### ISSUE THREAD

**Issue by PierrickI3** [awslabs/aws-athena-query-federation#776]
I am trying to connect QuickSight to my DynamoDB tables. I followed [this](https://dev.to/aws-builders/finally-dynamodb-support-in-aws-quicksight-sort-of-2lbl) tutorial and also looked at (outdated) AWS pages.

When I try to query data from Athena, it runs for a long time and I see the following warnings in CloudWatch for the lambda function that was created:

```
WARN  DynamoDBMetadataHandler:239 - doGetTable: Unable to retrieve table qa-walkntalk from AWSGlue in database/schema default. Falling back to schema inference. If inferred schema is incorrect, create a matching table in Glue to define schema (see README)
com.amazonaws.services.glue.model.EntityNotFoundException: Database default not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 1b48aee7-ed1a-41ce-8ccc-8eba5173cbda; Proxy: null)
```

I can see the same warning about other tables. The query never runs.

Is using Athena the best way to connect DynamoDB to QuickSight? Are there alternatives?

Thanks

**Comment by henrymai** [comment]
You can get rid of the Glue warnings by defining a Glue Table, however, I don't think that would make the queries faster for you in QuickSight if it is running extremely slowly.

You should verify if the slowness if the query is coming from Athena or QuickSight (by just running your QuickSight query in Athena's console).

You can follow the documentation here to setup a Glue Table: https://docs.aws.amazon.com/athena/latest/ug/connectors-dynamodb.html#connectors-dynamodb-setting-up-databases-and-tables-in-aws-glue

You may also want to use a Glue Crawler to crawl your DynamoDB table instead of manually creating a Glue Table as well.
Here is a video on how to use a Glue Crawler to crawl your DynamoDB table (stop at 5:15): https://youtu.be/YXoJVgxaSco

After you stop at 5:15, you can try querying your Glue Table in Athena by doing:
"SELECT * FROM "lambda:your_ddb_connector_lambda_name"."default"."your_glue_table_name"

**Comment by PierrickI3** [comment]
Thanks. We ended up using a different solution via Snowflake.
