### ISSUE TITLE
[FEATURE] Support for BlazingSQL possible?

### ISSUE THREAD

**Issue by richiverse** [awslabs/aws-athena-query-federation#83]
https://docs.blazingdb.com/docs/using-blazingsql

**Comment by atennak1** [comment]
Thanks for the issue.  Can you clarify In what way do you want BlazingSQL support?  Do you mean within a Lambda connector?  I suppose that's possible but I don't see what benefit that would provide over standard Athena usage with S3.

**Comment by avirtuos** [comment]
I believe BlazingSQL is a GPU enhanced SQL engine. If I'm correct, this
would presumably provide fast access to data that fits within the GPU's
VRAM. Would be good to understand the usecases and confirm if this
understanding is correct since most of the perf gains of the GPU
aggregation and filtering would be nullified by the current Lambda based
connectors until we can push down aggregates.

**Comment by avirtuos** [comment]
@richiverse Per my reply on Dec 18th, can you give us a bit more detail about the use-cases you have in mind? It is my understanding that a typical reason for using BlazingSQL is to exploit the parallelism in the GGPU to achieve extremely low latency SQL queries (usually over a relatively small dataset). Given that the current federation model doesn't support aggregation pushdown and adds non-trivial latency (likely 1 sec+ on a p99 basis), would you still get value from a BlazingDB integration?

**Comment by hackett123** [comment]
This ticket never got any followup from the requester, and it does not seem like the current federation model is a good use case for this solution. That being said, if you are looking for a BlazingSQL connector, you can engage with your AWS support representative or account manager to get it onto the product team's radar. The Athena service team currently has no plans to add a new connector for BlazingSQL.

**Comment by hackett123** [comment]
Updating closure status.
