### ISSUE TITLE
[QUESTION] PostgreSQL connector dynamically change schema

### ISSUE THREAD

**Issue by rs-alexis** [awslabs/aws-athena-query-federation#987]
I have a question that I don't think is related to a bug or feature request. 

I've added the PostgreSQL Athena connector (my_postgres) and added following environment variable
```
default=postgres://jdbc:postgresql://postgres2.host:5432/default_database?user=sample&password=sample
```

the issue is that:
- I have to have the default database to connect to in the connection string (in that case `default_database`)
- But that also prevents me from dynamically calling any other database on the server:
```
SELECT * FROM my_postgres.default_database.table1; ## Works
SELECT * FROM my_postgres.another_database.my_table; ## Does not work
```

How could I dynamically query any database (Like I could do with the MySQL connector) using the Postgres connector?

**Comment by hackett123** [comment]
To be more explicitly clear, there is no good way to "dynamically" query any db in your Postgres instance. My proposal above means defining more data sources in your Athena console, and then re-using your lambda connector in order to access all of those connections.

Fundamentally, MySQL and Postgres have different hierarchies of how they structure their data, and this is a consequence of that.

**Comment by hackett123** [comment]
We haven't had any followups on this ticket in a while, I'm going to close it out. If there are further questions, please feel free to re-open, or open a feature request for us to look into further.
